"""
JARVIS V2 - Base Provider Interface
"""
from abc import ABC, abstractmethod
from typing import List, Dict, Any, Generator, Optional
from core.schemas import ChatMessage, ModelResponse, ToolCall

class BaseProvider(ABC):
    @abstractmethod
    def generate(self, messages: List[ChatMessage], model: str, extra_kwargs: Optional[Dict[str, Any]] = None) -> str:
        """Synchronously generates a full response."""
        pass

    @abstractmethod
    def stream_generate(self, messages: List[ChatMessage], model: str, extra_kwargs: Optional[Dict[str, Any]] = None) -> Generator[str, None, None]:
        """Yields text tokens as they are generated by the model."""
        pass

    def generate_with_tools(
        self,
        messages: List[ChatMessage],
        model: str,
        tools: List[Dict[str, Any]],
        extra_kwargs: Optional[Dict[str, Any]] = None
    ) -> ModelResponse:
        """Generates response with native tool calling."""
        # Default fallback implementation for providers without native function calling
        content = self.generate(messages, model, extra_kwargs)
        return ModelResponse(content=content, tool_calls=None)

